require('plugins')
require('keymappings')
require('nvim-cmp')
require('autopairs')
require('nvim-lspconfig')  -- MUST BE BEFORE 'lsp'
require('lsp')
require('comment')
require('gitsign-config')
require('which_key_config')
require('nvim-treesitter-config')
require('telescope_config')
require('dashboard-config')
require('barbar-config')
require('lualine-config')
require('dap-config')
require('config')
require('markdownpreview')
